import type { MemoryDoc } from "../types.js";

/**
 * Render the human-readable `INDEX.md` — one line per memory, grouped by type.
 * It exists so the vault reads well in a git diff and in plain editors; it is
 * regenerated on every change and is not a source of truth.
 */
export function renderIndex(docs: MemoryDoc[]): string {
  const sorted = [...docs].sort((a, b) => a.name.localeCompare(b.name));
  const byType = new Map<string, MemoryDoc[]>();
  for (const doc of sorted) {
    const list = byType.get(doc.frontmatter.type) ?? [];
    list.push(doc);
    byType.set(doc.frontmatter.type, list);
  }

  const lines: string[] = [
    "# Memory Index",
    "",
    `> Generated by SmartCopilot — ${sorted.length} ${sorted.length === 1 ? "memory" : "memories"}. Do not edit by hand.`,
    "",
  ];

  for (const type of [...byType.keys()].sort()) {
    lines.push(`## ${type}`, "");
    for (const doc of byType.get(type)!) {
      const desc = doc.frontmatter.description || "_(no description)_";
      const status = doc.frontmatter.status ? ` _(${doc.frontmatter.status})_` : "";
      lines.push(`- [[${doc.name}]] — ${desc}${status}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}
